### PR TITLE
Feature: add upload script/updating yml

### LINKED ISSUE #5: Autobuild CLI binary
There should be a full CI\CD (TravisCI based most likely) that autobuilds the CLI binary and pushes it to the github repo whenever an update is made to it.

### PR DESCRIPTION
**Pull request by jakobpederson**
Fixes #5 

## Proposed Changes

-The way it's set it seems that every pull_request will run the push the binary logic even if it's not approved, this might mean unapproved builds get pushed.
-Expanding on 1 - pushes should only really happen if the build originated by approved users (approved users being those that are part of a team in the nebula orginization with permissions to push to the nebula-cmd repo)
-The "skip ci" or "skip build" or "skip travis" keywords seems to be missing in the commit message, this will still cause travis to rerun twice on every push.
-for this to work in a secure fashion the "GITHUB_API_KEY" will need to be encrypted, this means it will only be available to approved users, the script doesn't seem to take this into account as well - https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml

### CODE REVIEW

**Comment by naorlivne** [comment]
LGTM

**Comment by naorlivne** [comment]
Had to make a few changes to get it to work fully but wouldn't have been possible without your help.

**Comment by jakobpederson** [comment]
Thanks! I'm sorry it took so long but am really glad for the opportunity to
help out.

**Comment by naorlivne** [comment]
Noting to apologize for, it's such a small project that any help right now is greatly appreciated.

**Comment by naorlivne** [comment]
Also not sure how your Python skills are (or even if interests you) but https://github.com/nebula-orchestrator/worker/issues/43 is related to both Travis and to the worker code so thought you might be interested in that as well.

**Comment by jakobpederson** [comment]
I'd be willing to give it a shot! Python is my preferred language anyway.

Thanks!

**Comment by naorlivne** [comment]
Great, if you don't mind then making a post at https://github.com/nebula-orchestrator/worker/issues/43 claiming that ticket? also let's have future communications about that ticket happen in it.

**Comment by jakobpederson** [comment]
Hey naorlivne,

I’m going to have to pull off on this for right now, just getting really
tied up with some other stuff. Sorry about that.

-Jake

**Comment by naorlivne** [comment]
No worries, thanks for your help regardless.

**Pull request merged**
