### PR TITLE
Enhancement: add shell build script. skip travis

### PR DESCRIPTION
**Pull request by jakobpederson**
Fixes # Autobuild CLI binary #5

## Proposed Changes

  -adds build script
  -adds keywords to stop recursive builds
  -

### CODE REVIEW

**Comment by naorlivne** [comment]
Thanks for the pull request but there are a couple of issues I see:

1. The way it's set it seems that every pull_request will run the push the binary logic even if it's not approved, this might mean unapproved builds get pushed.
2. Expanding on 1 - pushes should only really happen if the build originated by approved users (approved users being those that are part of a team in the nebula orginization with permissions to push to the nebula-cmd repo)
3. The "skip ci" or "skip build" or "skip travis" keywords seems to be missing in the commit message, this will still cause travis to rerun twice on every push.
4. for this to work in a secure fashion the "GITHUB_API_KEY" will need to be encrypted, this means it will only be available to approved users, the script doesn't seem to take this into account as well - https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml

Sorry if I seem a bit rough, I do appreciate your time on this regardless of code reviews not always being the most pleasant,

**Comment by jakobpederson** [comment]
> Thanks for the pull request but there are a couple of issues I see:
> 
> 1. The way it's set it seems that every pull_request will run the push the binary logic even if it's not approved, this might mean unapproved builds get pushed.
> 2. Expanding on 1 - pushes should only really happen if the build originated by approved users (approved users being those that are part of a team in the nebula orginization with permissions to push to the nebula-cmd repo)
> 3. The "skip ci" or "skip build" or "skip travis" keywords seems to be missing in the commit message, this will still cause travis to rerun twice on every push.
> 4. for this to work in a secure fashion the "GITHUB_API_KEY" will need to be encrypted, this means it will only be available to approved users, the script doesn't seem to take this into account as well - https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml
> 
> Sorry if I seem a bit rough, I do appreciate your time on this regardless of code reviews not always being the most pleasant,

No need to apologize, this is all very helpful. Thanks for the feedback!

**Comment by jakobpederson** [comment]
I was working on this and I had a question:
How do I go about setting up encryption in a way that I can hand over the repo to you?

**Comment by naorlivne** [comment]
Sent you an invite to be part of the maintainers group of the project, this will mean the encryption you set will be able to be used by all maintainers, (it also means you could push directly without a pull request but I trust that you realize why that's not a good idea).

seems to me that the only things missing of it so far is to have to have  "skip ci" or "skip build" or "skip travis" keywords in the autobuild travis pushes to github with (to avoid another Travis run) & to have the build/ folder ignored from being part of the push (only the dist folder should be added in the "git add" command rather then using . which adds everything to it), also everything in the build folder that's part of the pull request will need to be removed.

**Comment by jakobpederson** [comment]
I've changed it so you have to include RUN UPLOAD SCRIPT in the message to
activate the script otherwise it'll just ignore it. I've also added the
encryption though I'm not one hundred percent it's set up right, could you
take a look?

https://github.com/jakobpederson/nebula-cmd/tree/encryption-20190302

**Comment by naorlivne** [comment]
https://github.com/jakobpederson/nebula-cmd/blob/f3dc7d1d93b38f73f59f15a9ef7e6d488a1a2fd2/test/travis_ci_scripts/upload_nebulactl.sh#L19 
https://github.com/jakobpederson/nebula-cmd/blob/f3dc7d1d93b38f73f59f15a9ef7e6d488a1a2fd2/test/travis_ci_scripts/upload_nebulactl.sh#L17
shouldn't that be git add dist/nebulactl ?

https://github.com/jakobpederson/nebula-cmd/blob/f3dc7d1d93b38f73f59f15a9ef7e6d488a1a2fd2/.travis.yml#L11
Think you accidentally had 2 lines combined as it seems to be half a line of unittests and half a line of the upload script

**Comment by jakobpederson** [comment]
1.) I was hoping that the line directly underneath that would be adding the
dist:
git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed - nebulactl.py run
and pushed" dist

It seems to be just committing the dist on my end, but I can change it up
if you prefer.

2.) I've updated that line.

https://github.com/jakobpederson/nebula-cmd/tree/encryption-20190302

Thanks for the feedback!
Jake

**Comment by naorlivne** [comment]
Travis.yaml looks good, only thing is that according to https://stackoverflow.com/questions/18248177/how-to-git-commit-a-whole-folder it's still best to run the following inside the script as your commiting an entire folder not just a single file:

git add dist
git commit -m 'skip travis build $TRAVIS_BUILD_NUMBER pushed - nebulactl.py run and pushed' 

there is also the issue of the merge conflict of the dist/nebulactl & the build folder being part of the pull request so after fixing the the issue above think it will be best to have a pull request that only includes the travis.yaml and the build scripts in it without the rest of the gunk in it so it can be auto merged by github.

**Comment by jakobpederson** [comment]
I got a pull request here:
https://github.com/nebula-orchestrator/nebula-cmd/pull/18/

Let me know if there's anything you need changed.

Thanks!

**Comment by naorlivne** [comment]
Closing this in order of #18

**Pull request closed without merging**
